### ISSUE TITLE
Pairing Code

### ISSUE THREAD

**Issue by cneiman** [Aayush9029/Kenobi-Server#15]
![Screen Shot 17](https://user-images.githubusercontent.com/8082544/142901764-6e3f321a-5491-4a78-9c88-af7e9927f51f.png)

unsure what to do here, and have reinstalled the mac app both from the .zip and cli. 

macbook pro
macOS Big Sur 11.6.1
13-inch, 2020
2GHz i5

**Comment by Aayush9029** [comment]
You can run this command to get the pairing code.

`ifconfig | grep 'inet.*broadcast' | awk '{print $2}' | cut -d. -f4`

The code is basically the last numbers of your IP address.

Seems like I didn't account for different local ip

Are you using any sort of proxy or vpn? I'd love to get to the bottom of this!


---


You can also scroll to the bottom to Help and tap manual ip to add ip manually!

**Comment by cneiman** [comment]
Got it, that makes sense! 

No, no proxy or VPN running at the moment. I am on a 5GHz network, which is the only thing I can think of.

**Comment by cneiman** [comment]
Ah, I believe it will be due to my watch being on the 2.4GHz network, while my mac is on the 5GHz, correct?

**Comment by Aayush9029** [comment]
Right. That's a possibility.

Due to my strict privacy policy I've totally disable logging on Appstore version of the app. You can try running the cli version. It shows you detailed info 


Once you've installed via pip you can run this script
`python3 -c "from kenobi import Kenobi as k;k()"`

and look at the the connection logs.

Here's my output 


![Screen Shot 2021-11-22 at 1 20 37 PM](https://user-images.githubusercontent.com/43297314/142914661-e7b0311e-23fe-4048-a8d0-5db679a497ab.png)

---


I'm assuming you've already accepted accessibility settings on your Mac. You can verify that by going to launch app and tapping the YouTube icon.  If YouTube doesn't open up that means it's not in the same network.

**Comment by Aayush9029** [comment]
I've updated the macOS app, it should generate code properly in case of weird ips.

https://github.com/Aayush9029/KenobiSite/releases/download/v1.3/Kenobi.app.zip
